language: rust
install:
  - cargo build --release --verbose
script:
  - mkdir serve_me
  - printf "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n\t<title>Hello World</title>\n\t<meta charset=\"utf-8\" />\n</head>\n<body>\n\t<p><b>Hello World!</b></p>\n</body>\n</html>\n" > serve_me/index.html
  - target/release/main -a 127.0.0.1 -p 9000 -r serve_me &
  - sleep 2
  - wget http://localhost:9000 -O test.html
  - cat test.html
  - killall main

